name: Build and deploy Python project to Azure Function App - oktatest-func

on:
  push:
    branches:
      - develop
  workflow_dispatch:

env:
  AZURE_FUNCTIONAPP_NAME: 'oktatest-func'
  AZURE_FUNCTIONAPP_PACKAGE_PATH: '.'
  PYTHON_VERSION: '3.10'

jobs:
  build-and-deploy:
    name: Build and Deploy Python Function
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      # - name: Setup Python version
      #   uses: actions/setup-python@v5
      #   with:
      #     python-version: ${{ env.PYTHON_VERSION }}

      # - name: Create and start virtual environment
      #   run: |
      #     python -m venv venv
      #     source venv/bin/activate
      #     python -m pip install --upgrade pip
      #     pip install -r requirements.txt

      # Optional: Add step to run tests here

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_2A7474DD817A42E2AC76DF0C4A95365B }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_99A7DC14B1A24F138BB141A2C322D4FF }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_E4962104DC1341F9B898CEA99DA200D1 }}

      - name: 'Deploy to Azure Functions'
        uses: Azure/functions-action@v1
        id: deploy-to-function
        with:
          app-name: ${{ env.AZURE_FUNCTIONAPP_NAME }}
          slot-name: 'Production'
          package: ${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}
          sku: flexconsumption
          remote-build: true